config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :sessions
  resources :teams
  resources :studies
  resources :participants do
    resources :notes
  end
  resources :users

  root to: "users#home"
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'users/:id/home', to: 'users#home', :as => :user_home

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pending_users' => 'users#pending'
  get '/inactive_users' => 'users#inactive'
  get '/approved_users' => 'users#approved'
  get '/denied_users' => 'users#denied'
  get '/admin_users' => 'users#admin'
  get '/notification_calendar' => 'users#notification_calendar'

  put '/remove_admin_rights/:id' => 'users#remove_admin_rights', :as => :remove_admin_rights
  put '/add_admin_rights/:id' => 'users#add_admin_rights', :as => :add_admin_rights
  put '/approve_user/:id' => 'users#approve_user', :as => :approve_user
  put '/reject_user/:id' => 'users#reject_user', :as => :reject_user

  get '/reset_password' => 'users#reset_password'
  post '/reset_password' => 'users#change_password'

  get '/forgot_password' => 'users#forgot_password'
  post '/forgot_password' => 'users#request_password'

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :participant
  belongs_to :user

  validates :note_text, presence: true
  validates :important, inclusion: { in: [true, false] }

  validates :notify, inclusion: { in: [true, false] }
  validates :notify_on, presence: true, if: :notify?

  validates :isDone, inclusion: { in: [true, false] }
  validates :doneBy, presence: true, if: :isDone?
  validates :doneOn, presence: true, if: :isDone?

  validates :isPinned, inclusion: { in: [true, false] }

  validates :participant_id, presence: true
  validates :user_id, presence: true
  validates :updated_by, presence: true

  before_validation :set_doneOn, if: :isDone_changed?
  before_validation :set_notification

  scope :recent_ten, -> {
    order("updated_at desc").limit(10)
  }

  scope :upcoming_notifications_this_week, -> {
    where(notify: true).where(:notify_on => Date.today.beginning_of_week..Date.today.end_of_week).order(:notify_on)
  }

  scope :upcoming_notifications_this_fortnight, -> {
    where(notify: true).where(:notify_on => Date.today.beginning_of_week..Date.today.end_of_week + 7).order(:notify_on)
  }

  scope :upcoming_notifications_this_month, -> {
    where(notify: true).where(:notify_on => Date.today.beginning_of_month..Date.today.end_of_month).order(:notify_on)
  }

  scope :upcoming_notifications, -> {
    where(notify: true).order(:notify_on)
  }

  scope :major, -> {
    where(important: true)
  }

  # Maximum notes per page.
  self.per_page = 10

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |note|
        csv << note.attributes.values_at(*column_names)
      end
    end
  end

  private

  def note_notifier_notification
    NotifierMailer.note_notifier(self).deliver
  end

  def set_notification
    unless self.notify?
      self.notify_on = nil
    end
  end

  def set_doneOn
    if self.isDone?
      self.doneOn = DateTime.now
      self.doneBy = self.updated_by
    else
      self.doneOn = nil
      self.doneBy = nil
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :get_user_from_session # authorize is done here.
  before_action :get_participant
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  after_action :set_participant_last_contact, only: [:create, :update]


  # GET /notes
  # GET /notes.json
  def index
    @all_participant_notes = @participant.notes.order("notes.updated_at desc").paginate(:page => params[:page], :per_page => 16)

    respond_to do |format|
      format.html
      format.csv { send_data @participant.notes.order("notes.updated_at desc").to_csv }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new(user_id: @user.id)
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @participant.notes.new(note_params)
    @note.user_id = @user.id
    @note.updated_by = @user.id
    
    respond_to do |format|
      if @note.save
        format.html { redirect_to [@participant,@note], notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to [@participant,@note], notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to participant_path(@participant), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_user_from_session
      authorize()
      @user = @current_user
    end

    def get_participant
      @participant = Participant.find(params[:participant_id])
    end

    def set_note
      @note = Note.find(params[:id])
    end

    def set_participant_last_contact
      @participant.update(last_contacted_at: @note.updated_at, last_contacted_by: @current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      get_user_from_session()
      params.require(:note).permit(:participant_id, :note_text, :important, :notify_on, :updated_by, :notify, :isDone, :isPinned)
    end

    def participant_params
      params.require(:participant).permit(:name, :gender, :contact_number, :home_address, :active, :study_id, :date_of_birth, :email, :last_contacted_by, :last_contacted_at)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for([@participant,@note]) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group  col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= f.input :note_text, as:"text", label: false, input_html: {class: "sticky_editor form-control"} %><br/>
    </div>
    <div class="actions form-inline col-xs-6 col-sm-6 col-md-6 col-lg-6" align="center">
      <%= f.check_box :notify, data: { toggle: 'toggle', on: 'Notify On', onstyle: 'primary', off: 'Notify Off', offstyle: 'default', width: '100'}, label: '' %> <br/>
      <%= f.input :notify_on, as:"datetime_picker", label: false, input_html: { data: {date_options: {defaultDate: DateTime.now.next_week.at_beginning_of_minute, format:"LLLL", sideBySide: true}}, class: "form-control"}   %><br/>

      <%= f.check_box :isDone, data: { toggle: 'toggle', on: 'Done', onstyle: 'primary', off: 'Not Done', offstyle: 'default', width: '85'} %>
      <%= f.check_box :important, data: { toggle: 'toggle', on: 'Important', onstyle: 'danger', off: 'Not Important', offstyle: 'default', width: '120'}, label: '' %><br />
      
      <%= f.input :isPinned, as:"hidden", input_html: { value: false } %><br />
      <%= f.input :updated_by, as:"hidden", input_html: { value: @current_user.id } %><br/>
      <%= f.submit "Save Note", class:"btn btn-primary" %>
      <%= link_to 'Back', :back, class:"btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note for <%= link_to @note.participant.first_name, participant_path(@note.participant) %> <%= link_to @note.participant.surname, participant_path(@note.participant) %></h1>
<p id="notice"><%= notice %></p>
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1>Showing All Notes for Participant (<%=@participant.first_name%> <%=@participant.surname%>)</h1>
<p id="notice"><%= notice %></p>
<p>
  <%= link_to 'Logg New Note', new_participant_note_path(@participant), class:"btn btn-primary" %> 
  <%= link_to "Export to CSV", participant_notes_path(format: "csv"), class:"btn btn-info" %> 
    <%= link_to "Back to " + @participant.first_name + "'s page", participant_path(@participant), class:"btn btn-danger" %>
</p>
<table class='table table-striped sortable'>
  <thead>
    <tr>
      <th>Last Modified</th>
      <th data-defaultsort='disabled'>Note text</th>
      <th>Important</th>
      <th>User</th>
      <th>Notify on</th>
      <th colspan="2" data-defaultsort='disabled'>Manage</th>
    </tr>
  </thead>

  <tbody>
    <% @all_participant_notes.each do |note| %>
      <tr>
        <td><%= time_ago_in_words(note.updated_at)%> ago</td>
        <td><%= note.note_text %></td>
        <td><%= note.important %></td>
        <td><%= link_to note.user.full_name, note.user if note.user %></td>
        <% if note.notify? %>
          <td><%= note.notify_on %></td>
        <% else %>
          <td>Notification Off</td>
        <% end %>

        <% if @current_user.isAdmin? || (@current_user.id == note.user.id) %>
          <td><%= link_to 'Edit', edit_participant_note_path(note.participant_id,note.id) %></td>
          <td><%= link_to 'Destroy', participant_note_path(note.participant_id,note.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate(@all_participant_notes) %>
<br>

app/views/notes/new.html.erb
<h1>New Note for <%= link_to @participant.first_name, participant_path(@participant) %> <%= link_to @participant.surname, participant_path(@participant) %></h1>

<%= render 'form', participant: @participant, note: @note, user: @user_id %>

app/views/notes/show.html.erb
<h2><%= image_tag("icon/png/flag-4.png", size:"40x40", title:"Important!!!") if @note.important? %> Note for <%= link_to @note.participant.first_name, participant_path(@note.participant) %> <%= link_to @note.participant.surname, participant_path(@note.participant) %></h2>
<p id="notice"><%= notice %></p>
<p class="post_it_note_show">
  "<%= @note.note_text %>"
</p>

<p><%= image_tag("icon/png/note.png", size:"40x40", title:"Created by") %>  <%= link_to @note.user.full_name + ' (' +@note.user.email + ')', @note.user %> <%= @note.created_at.strftime('%A %y-%b-%e at %I:%M%p') %></p>
<% if @note.user_id != @note.updated_by %>
	<p><%= image_tag("icon/png/edit.png", size:"40x40", title:"Edited by") %>  <%= link_to User.find(@note.updated_by).full_name + ' (' + User.find(@note.updated_by).email + ')', user_path(@note.updated_by) %> <%= @note.updated_at.strftime('%A %y-%b-%e at %I:%M%p') %></p>
<% end %>

<% if @note.notify? %>
	<p><%= image_tag("icon/png/alarm-clock.png", size:"40x40", title:"Notification") %>  <%= @note.notify_on.strftime('%A %y-%b-%e at %I:%M%p') %></p>
<% end %>

<% if @note.isDone? %>
	<p><%= image_tag("icon/png/checked-1.png", size:"40x40", title:"Done") %>  <%= @note.doneOn.strftime('%A %y-%b-%e at %I:%M%p') %> by <%= link_to(User.find(@note.doneBy).full_name, User.find(@note.doneBy)) if @note.doneBy.present? %></p>
<% end %>

<%= link_to 'Edit', edit_participant_note_path(@participant,@note), class:"btn btn-danger" %>
<%= link_to 'Back', participant_notes_path(@participant), class:"btn btn-warning"  %>