config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :sessions
  resources :teams
  resources :studies
  resources :participants do
    resources :notes
  end
  resources :users

  root to: "users#home"
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'users/:id/home', to: 'users#home', :as => :user_home

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pending_users' => 'users#pending'
  get '/inactive_users' => 'users#inactive'
  get '/approved_users' => 'users#approved'
  get '/denied_users' => 'users#denied'
  get '/admin_users' => 'users#admin'
  get '/notification_calendar' => 'users#notification_calendar'

  put '/remove_admin_rights/:id' => 'users#remove_admin_rights', :as => :remove_admin_rights
  put '/add_admin_rights/:id' => 'users#add_admin_rights', :as => :add_admin_rights
  put '/approve_user/:id' => 'users#approve_user', :as => :approve_user
  put '/reject_user/:id' => 'users#reject_user', :as => :reject_user

  get '/reset_password' => 'users#reset_password'
  post '/reset_password' => 'users#change_password'

  get '/forgot_password' => 'users#forgot_password'
  post '/forgot_password' => 'users#request_password'

end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :notes
  has_many :users, through: :notes
  belongs_to :study

  enum gender: ['Male','Female','Others','Unspecified']
  enum status: ['Interested','Recruited','Included','Withdrawn','Excluded','Completed']
  enum primary_contact_number_type: ['Home','Mobile','Work']
  enum secondary_contact_number_type: ['Home ','Mobile ','Work ']

  scope :recently_contacted, -> {
    order("last_contacted_at desc").distinct.limit(10)
  }

  validates :first_name, presence: true
  validates :surname, presence: true
  #validates :email, :format => EMAIL_REGEX
  validates :status, exclusion: { in: [nil] }
  #validates :gender, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |participant|
        csv << participant.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authorize
  before_action :check_for_exisiting_study, except: [:index, :show, :destroy]
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  # GET /participants
  # GET /participants.json
  # GET /participants.csv
  def index
    @participants = Participant.all.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html
      format.csv { send_data @participants.to_csv }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    if @participant.last_contacted_by.nil?
      @last_contacted_by_name = 'No calls logged yet.'
    else
      @last_contacted_by_name = User.find(@participant.last_contacted_by).full_name
    end
    @participant_recent_notes = @participant.notes.order("updated_at desc").paginate(:page => params[:page])

  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def check_for_exisiting_study
      @current_studies = Study.all
      if @current_studies.empty?
        redirect_to new_study_path, notice: 'We need at least one active study to start creating participants.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:participants_system_id, :first_name, :surname, :preferred_name, :title, :gender, :primary_contact_number, :primary_contact_number_type, :secondary_contact_number, :secondary_contact_number_type, :home_address_line_1, :home_address_line_2, :home_address_suburb, :home_address_state, :home_address_postcode, :mailing_address_line_1, :mailing_address_line_2, :mailing_address_suburb, :mailing_address_state, :mailing_address_postcode, :status, :study_id, :date_of_birth, :email, :last_contacted_by, :last_contacted_at)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= bootstrap_form_for(participant, label_errors: true) do |f| %>
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="form-inline">
      <div class="form-group col-xs-4">
        <%= f.collection_select(:study_id, @current_studies, :id, :study_name, label: "Study") %>
      </div>
      <div class="form-group col-xs-2">
        <%= f.text_field :participants_system_id, label: "System ID" %>
      </div>
      <div class="form-group col-xs-2">
        <%= f.select :status, Participant.statuses.keys.to_a, label: "Status" %>
      </div>
    </div>
  </div>
  <br/><br/>
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.text_field :title, label: "Title" %> <%= f.text_field :surname, label: "Surname" %> <%= f.text_field :first_name, label: "First Name" %> <%= f.text_field :preferred_name, label: "Preferred Name" %>
    </div>
    <div class="form-group col-xs-4">
      <%= f.text_field :email, label: "E-mail Address" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-2">
      <%= f.select :gender, Participant.genders.keys.to_a, label: "Gender" %>
    </div>
    <div class="form-group col-xs-2">
      <%= f.text_field :date_of_birth, label: "Birth Date", data: { provide: 'datepicker'} %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.text_field :primary_contact_number, label: "Primary Contact Number" %>
    </div>
    <div class="form-group col-xs-2">
      <%= f.select :primary_contact_number_type, Participant.primary_contact_number_types.keys.to_a, label: "Type" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.text_field :secondary_contact_number, label: "Secondary Contact Number" %>
    </div>
    <div class="form-group col-xs-2">
      <%= f.select :secondary_contact_number_type, Participant.secondary_contact_number_types.keys.to_a, label: "Type" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-6">
      <%= f.label 'Home' %>
      <%= f.text_field :home_address_line_1, label: 'Address Line 1' %>
      <%= f.text_field :home_address_line_2, label: 'Address Line 2' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-2"><%= f.text_field :home_address_suburb, label: 'Suburb' %></div>
    <div class="form-group col-xs-2"><%= f.text_field :home_address_state, label: 'State' %></div>
    <div class="form-group col-xs-2"><%= f.text_field :home_address_postcode, label: 'Post Code' %></div>
  </div>
  <div class="row">
    <div class="form-group col-xs-6">
      <%= f.label 'Mailing' %>
      <%= f.text_field :mailing_address_line_1, label: 'Address Line 1' %>
      <%= f.text_field :mailing_address_line_2, label: 'Address Line 2' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-2"><%= f.text_field :mailing_address_suburb, label: 'Suburb' %></div>
    <div class="form-group col-xs-2"><%= f.text_field :mailing_address_state, label: 'State' %></div>
    <div class="form-group col-xs-2"><%= f.text_field :mailing_address_postcode, label: 'Post Code' %></div>
  </div>

  <div class="actions">
    <%= f.submit "Save Changes", class: "btn btn-success" %>
    <%= link_to 'Cancel', :back, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Update Participant Information</h1>

<%= render 'form', participant: @participant %>

app/views/participants/find_participant_form.html.erb
<%= form_for(participant) do |f| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Find Participant By Name' %>
    <%= f.text_field :search_string%>
  </div>

  <div class="actions">
    <%= f.submit 'Find Participant' %>
  </div>
<% end %>

app/views/participants/index.html.erb
<h1>All Participants</h1>
<p id="notice"><%= notice %></p>
<% unless @participants.nil? || @participants.empty? %>
  <p>
    <%= link_to 'Register New Participant', new_participant_path, class:"btn btn-warning" %> 
    <%= link_to "Export to CSV", participants_path(format: "csv"), class: 'btn btn-info' %>
  </p>
  <table class='table table-striped sortable'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Surname</th>
        <th>First Name</th>
        <th>Preferred Name</th>
        <th>Gender</th>
        <th>Primary Contact Number</th>
        <th>Secondary Contact Number</th>
        <th data-defaultsort='disabled'>State</th>
        <th>Post Code</th>
        <th>Status</th>
        <th>Study</th>
        <th>Birthdate</th>
        <th>E-mail Address</th>
        <% if @current_user.isAdmin? %>
          <th colspan="2" data-defaultsort='disabled'></th>
        <% else %>
          <th data-defaultsort='disabled'></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= participant.title %></td>
          <td><%= link_to participant.surname, participant %></td>
          <td><%= link_to participant.first_name, participant %></td>
          <td><%= participant.preferred_name %></td>
          <td><%= participant.gender %></td>
          <td><%= participant.primary_contact_number %> (<%= participant.primary_contact_number_type %>)</td>
          <td><%= participant.secondary_contact_number %> <%= participant.secondary_contact_number_type %></td>
          <td><%= participant.home_address_state %></td>
          <td><%= participant.home_address_postcode %></td>
          <td><%= participant.status %></td>
          <td><%= participant.study.study_name %></td>
          <td><%= participant.date_of_birth %></td>
          <td><%= participant.email %></td>
          <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
          <% if @current_user.isAdmin %>
            <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(@participants) %>
<% end %>
<p>
  <%= link_to 'Register New Participant', new_participant_path, class:"btn btn-warning" %> 
  <%= link_to "Export to CSV", participants_path(format: "csv"), class: 'btn btn-info' %>
</p>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>
<p align="center">
  <div class="toppad container-fluid ">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @participant.title %> <%= @participant.first_name %> <%= @participant.surname %> [<%= @participant.status %>]</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3" align="center">
            <%= image_tag("https://www.barfoot.co.nz/images/noprofile-big.png", class:"img-circle img-responsive", title:"You look so cute on this one.", size:"150x150") %><br/>
            <%= link_to "Edit Profile", edit_participant_path(@participant), class:"btn btn-danger" %>
          </div>
          <div class="col-md-9 col-lg-9"> 
            <table class="table table-user-information table-striped">
              <tbody>
                <% if @participant.study.present? %>
                  <tr>
                    <td class="attribute_data">Study</td>
                    <td><%= link_to @participant.study.study_name, @participant.study %></td>
                  </tr>
                <% end %>
                <% if @participant.participants_system_id.present? %>
                  <tr>
                    <td class="attribute_data">System ID</td>
                    <td><%= @participant.participants_system_id %></td>
                  </tr>
                <% end %>
                <% if @participant.date_of_birth.present? %>
                  <tr>
                    <td class="attribute_data">Age</td>
                    <td><%=(Date.today.year - @participant.date_of_birth.year).to_s %></td>
                  </tr>
                <% end %>
                <% if @participant.primary_contact_number.present? %>
                  <tr>
                    <td class="attribute_data">Primary Contact Number</td>
                    <td><%= @participant.primary_contact_number %> (<%= @participant.primary_contact_number_type %>)</td>
                  </tr>
                <% end %>
                <% if @participant.secondary_contact_number.present? %>
                  <tr>
                    <td class="attribute_data">Secondary Contact Number</td>
                    <td><%= @participant.secondary_contact_number %> (<%= @participant.secondary_contact_number_type %>)</td>
                  </tr>
                <% end %>
                <% if @participant.home_address_line_1.present? %>
                  <tr>
                    <td class="attribute_data">Home Address</td>
                    <td><%= @participant.home_address_line_1 %> <%= @participant.home_address_line_2 %>, <%= @participant.home_address_suburb %>, <%= @participant.home_address_state %>, <%= @participant.home_address_postcode %></td>
                  </tr>
                <% end %>
                <% if @participant.mailing_address_line_1.present? %>
                  <tr>
                    <td class="attribute_data">Mailing Address</td>
                    <td><%= @participant.mailing_address_line_1 %> <%= @participant.mailing_address_line_2 %>, <%= @participant.mailing_address_suburb %>, <%= @participant.mailing_address_state %>, <%= @participant.mailing_address_postcode %></td>
                  </tr>
                <% end %>
                <% if @participant.gender.present? %>
                  <tr>
                    <td class="attribute_data">Gender</td>
                    <td><%= @participant.gender %></td>
                  </tr>
                <% end %>
                <% if @participant.email.present? %>
                  <tr >
                    <td class="attribute_data">Email</td>
                    <td><%= @participant.email %></td>
                  </tr>
                <% end %>
                <% if @participant.last_contacted_by.present? %>
                  <tr >
                    <td class="attribute_data">Last Contact</td>
                    <td>
                      <%= link_to @last_contacted_by_name, user_path(@participant.last_contacted_by) %> 
                      <%= time_ago_in_words(@participant.last_contacted_at) %> ago.
                    </td>
                  </tr>
                <% end %>
                <tr class="container-fluid">
                  <td class="attribute_data">Joined</td>
                  <td><%= @participant.registeredOn if @participant.registeredOn.present? %><%= (" by user " + User.find(@participant.registeredBy)) if @participant.registeredBy.present? %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</p>
<p align="center">
  <%= link_to 'Back to All Participants', participants_path, class:"btn btn-success" if @current_user.isAdmin? %> 
  <%= link_to 'Logg New Note for ' +  + @participant.first_name, new_participant_note_path(@participant), class:"btn btn-warning" %> 
  <%= link_to "Show all of " + @participant.first_name + "'s Notes", participant_notes_path(@participant), class:"btn btn-primary" %>
  <%= link_to "Export Notes to CSV", participant_notes_path(@participant, format: "csv"), class:"btn btn-info" %> 
</p>