config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :sessions
  resources :teams
  resources :studies
  resources :participants do
    resources :notes
  end
  resources :users

  root to: "users#home"
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'users/:id/home', to: 'users#home', :as => :user_home

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pending_users' => 'users#pending'
  get '/inactive_users' => 'users#inactive'
  get '/approved_users' => 'users#approved'
  get '/denied_users' => 'users#denied'
  get '/admin_users' => 'users#admin'
  get '/notification_calendar' => 'users#notification_calendar'

  put '/remove_admin_rights/:id' => 'users#remove_admin_rights', :as => :remove_admin_rights
  put '/add_admin_rights/:id' => 'users#add_admin_rights', :as => :add_admin_rights
  put '/approve_user/:id' => 'users#approve_user', :as => :approve_user
  put '/reject_user/:id' => 'users#reject_user', :as => :reject_user

  get '/reset_password' => 'users#reset_password'
  post '/reset_password' => 'users#change_password'

  get '/forgot_password' => 'users#forgot_password'
  post '/forgot_password' => 'users#request_password'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :members, class_name: "User", foreign_key: "supervisor_id"
  has_many :notes
  has_many :participants, through: :notes

  belongs_to :team
  belongs_to :supervisor, class_name: "User", optional: true

  validates :email, presence: true, uniqueness: true, :format => EMAIL_REGEX
  validates :password, presence: true, confirmation: true
  validates :contact_number, presence: true
  validates :full_name, presence: true
  validates :team_id, presence: true, numericality: true

  #validates :isActive, inclusion: { in: [true, false] }
  #validates :isApproved, inclusion: { in: [true, false] }
  #validates :isAdmin, inclusion: { in: [true, false] }
  #validates :isDenied, inclusion: { in: [true, false] }
  #validates :isSupervisor, inclusion: { in: [true, false] }

  before_save :encrypt_password, if: :password_changed?

  after_initialize :init

  def new_user_registration_email
    # UserMailer.new_registration_email_for_user(self).deliver

    # Get all active approved admins
    admins = User.where(isAdmin: true).where(isApproved: true).where(isActive: true)

    # Send an email to all admins
    # admins.each do |admin|
      # UserMailer.new_registration_email_for_admins(self,admin.email).deliver
    # end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

  private
    def init
    # Set initial values - they are always false since the admins will change their values via the approval.
        if self.isActive.nil?
          self.isActive = false
        end
        if self.isApproved.nil?
          self.isApproved = false
        end
        if self.isAdmin.nil?
          self.isAdmin = false
        end
        if self.isDenied.nil?
          self.isDenied = false
        end
        if self.isSupervisor.nil?
          self.isDenied = false
        end
    end

    def encrypt_password
        self.password= Digest::MD5.hexdigest(password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create, :forgot_password, :request_password, :change_password, :reset_password, :pending]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_admin_rights, :remove_admin_rights, :approve_user, :reject_user]
  before_action :set_user_by_email, only: [:change_password]
  # might be unsafe to include get function reset_password
  before_action :create_session_by_auth_email, only: [:pending]
  before_action :require_admin, only: [:index, :pending, :approved, :denied, :inactive, :admin, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/pending
  # Pending means not approved or denied
  def pending 
    @pending_users = User.where(isApproved:false).where(isDenied:false).paginate(:page => params[:pending_users_page], :per_page => 10)
  end

  # GET /users/approved
  # Already approved but might need to promote to admin/deactivate
  def approved
    @approved_users = User.where(isApproved:true).where(isDenied:false).paginate(:page => params[:uapproved_users_page], :per_page => 10)
  end

  # GET /users/denied
  # Already denied but might need to approve
  def denied
    @denied_users = User.where(isDenied:true).where(isApproved:false).paginate(:page => params[:denied_users_page], :per_page => 10)
  end

  # GET /users/inactive
  # Already inactive but might need to activate
  def inactive
    @inactive_users = User.where(isActive:false).paginate(:page => params[:inactive_users_page], :per_page => 10)
  end

  # GET /users/admin
  # Manage all admin users/remove admin rights
  def admin
    @admin_users = User.where(isAdmin:true).where(isApproved:true).paginate(:page => params[:admin_users_page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /notification_calendar
  def notification_calendar
    get_upcoming_users_notifications_and_major_team_notifications

    @notifications = @upcoming_users_notifications_and_major_team_notifications

    respond_to do |format|
      format.html
      # format.csv { send_data @participant.notes.order("updated_at desc").to_csv }
    end
  end

  # GET /users/1/home
  def home
    # Get all active studies (for filter)
    get_active_studies()

    # Recently Contacted Participants:
    get_recently_contacted_participants()

    # Upcoming Notifications (This Week)
    get_upcoming_notifications() 

    # Your Recent Notes:
    get_recent_notes_from_user()

  end

  # GET /users/new
  def new
    if Team.none?
      redirect_to new_team_path, notice: 'No team exists. You need at least one to begin.'
    end
    @user = User.new
  end

  def forgot_password
    @errors = []
  end

  def request_password
    @errors = []
    if @user
      UserMailer.password_reset(@user).deliver
      redirect_to forgot_password_path, notice: 'Instructions sent by email'
    else
      @errors << "Invalid Email"
      render :forgot_password
    end

  end

  def reset_password
    @errors = []
  end

  def change_password
    @errors = []

    if @user
      if params[:password] == params[:password_confirmation]
        @user.password = params[:password]
        if  Digest::MD5.hexdigest(@user.email) == params[:token] 
          if @user.save
            @current_user = @user
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'Password successfully updated.'
          else
            @errors << "Something went wrong"
            render :reset_password
          end
        else
          @errors << "Invalid Recovery Token"
          render :reset_password
        end
      else
        @errors << "Passwords don't match"
        render :reset_password
      end
    else
      @errors << "Invalid Email"
      render :reset_password
    end
  end

  # GET /users/1/edit
  def edit
    redirect_to user_path(@user.id), notice: 'You are not authorized to make modifications to this user.' unless (@current_user.isAdmin?) || (@current_user.id == @user.id)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.new_user_registration_email
        format.html { redirect_to login_path, notice: 'User was successfully created. Please see email for Instructions.'
                    }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, notice: 'Fix the errors.'}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_home_path(@current_user), notice: 'User (' + @user.full_name + ') was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /users/1
  def activate
    set_user_isActive(true)
  end

  # PATCH/PUT /users/1
  def deactivate
    set_user_isActive(false)
  end

  # PATCH/PUT /users/1
  def add_admin_rights
    set_admin_rights(true)
  end

  # PATCH/PUT /users/1
  def remove_admin_rights
    set_admin_rights(false)
  end

  # PATCH/PUT /users/1
  def approve_user
    @errors = []
    if @user
      @user.isActive = true
      @user.isApproved = true
      @user.isDenied = false  
      if @user.save
        UserMailer.registration_approved(@user,@current_user.email).deliver
        redirect_to pending_users_path, notice: 'User has been approved.'
      else
        redirect_to pending_users_path, notice: 'Something went wrong.'
      end
    else
      redirect_to pending_users_path, notice: 'Invalid Email.'
    end
  end

  # PATCH/PUT /users/1
  def reject_user
    @errors = []
    if @user
      @user.isActive = true
      @user.isApproved = false
      @user.isDenied = true 
      if @user.save
        UserMailer.registration_denied(@user,@current_user.email).deliver
        redirect_to pending_users_path, notice: 'User has been denied access.'
      else
        redirect_to pending_users_path, notice: 'Something went wrong.'
      end
    else
      redirect_to pending_users_path, notice: 'Invalid Email/User.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id].present?
        @user = User.find(params[:id])
      end
    end

    def set_current_user_by_email
      @user = User.where(email: params[:email]).where(isActive: true).first
      if @user.nil?
        redirect_to root_path, notice: "That email is either invalid or deactivated. Contact your admins."
      else
        # this is for the instance of get_password where a user is signed in but changing passwords.
        @current_user = @user
      end
    end

    def set_user_by_email
      @user = User.where(email: params[:email]).where(isActive: true).first
      if @user.nil?
        redirect_to root_path, notice: "That email is either invalid or deactivated. Contact your admins."
      end
    end

    def set_user_isActive(isActive)
      @errors = []
      if @user
        @user.isActive = isActive
        toggle_notice = (@user.isActive)? ("User is now active.") : ("User deactivated.")
        if @user.save
          # UserMailer.approve_account(@user).deliver
          # Send email to notify user that he is now active or not.
          redirect_to inactive_users_path, notice: toggle_notice
        else
          redirect_to inactive_users_path, notice: 'Something went wrong. Email not sent'
        end
      else
        redirect_to inactive_users_path, notice: 'Invalid Email/User.'
      end
    end

    def set_admin_rights(isAdmin)
      @errors = []
      if @user
        @user.isAdmin = isAdmin 
        toggle_notice = (@user.isAdmin)? ("User is now admin.") : ("Admin rights revoked.")
        if @user.save
          # UserMailer.approve_account(@user).deliver
          # Send email to notify user that he is now admin.
          redirect_to pending_users_path, notice: toggle_notice
        else
          redirect_to pending_users_path, notice: 'Something went wrong. Email not sent'
        end
      else
        redirect_to pending_users_path, notice: 'Invalid Email/User.'
      end
    end

    def get_recently_contacted_participants
      if params[:filter_participants_by_study].blank? # All Studies
        study_filter = 0
      else
        study_filter = params[:filter_participants_by_study][:filter_participants_by_study_val]
      end
      if params[:search].nil? || params[:search].blank?
        if study_filter.present? && study_filter != 0 # Study Selected
          @search_participants = @current_user.participants.recently_contacted.where(study_id: study_filter)
        else # All Studies
          @search_participants = @current_user.participants.recently_contacted
        end
        @search_or_recent_header = 'Recently Contacted Participants:'
        @if_empty_string = 'No Participants Contacted Yet.'   
      else
        if study_filter.present? && study_filter != 0 # Study Selected
          @search_participants = Participant.where(params[:field_to_search] + " LIKE '%#{params[:search]}%'").where(study_id: study_filter)
        else # All Studies
          @search_participants = Participant.where(params[:field_to_search] + " LIKE '%#{params[:search]}%'")
        end
        @search_or_recent_header = 'Found ' + @search_participants.count.to_s + ' Participants'

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_reset_password.html.erb
<%= bootstrap_form_tag url: reset_password_path do |f| %>
  <% if @errors.any? %>
    <div class="alert alert-danger">
      <% @errors.each do |message| %>
        <li class="error"><%= message %></li>
      <% end %>
    </div>
  <% end %>
  <%= hidden_field_tag :email, params[:email] %>
  <%= hidden_field_tag :token, params[:token] %>
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="row">
    <div class="actions form-group col-xs-4">
      <%= submit_tag "Reset Password", class: "btn btn-success" %>
      <%= link_to "Go Back - I just remembered.", :back, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/users/admin.html.erb
<p id="notice"><%= notice %></p>
<% if @admin_users.empty? %>
  <h2>You have no admins. Maybe you should be president.</h2>
<% else %>
  <h1>Admin Users</h1>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Full name</th>
        <th>Email/Username</th>
        <th>Contact number</th>
        <th>Team</th>
        <th>Supervisor</th>
        <th>Admin?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_users.each do |user| %>
        <tr>
          <td><%= link_to user.full_name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.contact_number %></td>
          <td><% unless user.team_id.nil? %> <%= link_to Team.find(user.team_id).name, Team.find(user.team_id) %><%end%></td>
          <td><% if user.supervisor_id.nil? %>
                <% unless user.supervisorNameNotAUser.nil? %>
                  <%= user.supervisorNameNotAUser %>
                <% end %>
              <% else %>
                <%= link_to User.find(user.supervisor_id).full_name, user_path(user.supervisor_id) %>
              <% end %>
          </td>
          <td>  <% if user.isAdmin? %>
                  <%=link_to 'Remove Admin Rights', remove_admin_rights_path(user.id), method: :put%>
                <% else %>
                  <%=link_to 'Set as Admin', add_admin_rights_path(user.id), method: :put%>
                <% end %>
          </td>
          <td><%= link_to 'Approve', approve_user_path(user.id), method: :put %></td>
          <td><%= link_to 'Reject' , reject_user_path(user.id), method: :put %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/all_admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Pending Approval</h1>
<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email/Username</th>
      <th>Contact number</th>
      <th>Team</th>
      <th>Supervisor</th>
      <th>Admin?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pending_users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_number %></td>
        <td><% unless user.team_id.nil? %> <%= link_to Team.find(user.team_id).name, Team.find(user.team_id) %><%end%></td>
        <td><% if user.supervisor_id.nil? %>
              <% if user.supervisorNameNotAUser.nil? %>
                <%= user.supervisorNameNotAUser %>
              <% end %>
            <% else %>
              <%= link_to User.find(user.supervisor_id).name, user_path(user.supervisor_id) %>
            <% end %>
        </td>
        <td>  <% if user.isAdmin? %>
                <%=link_to 'Remove Admin Rights', remove_admin_rights_path(user.id), method: :put%>
              <% else %>
                <%=link_to 'Set as Admin', add_admin_rights_path(user.id), method: :put%>
              <% end %>
        </td>
        <td><%= link_to 'Approve', approve_user_path(user.id), method: :put %></td>
        <td><%= link_to 'Reject' , reject_user_path(user.id), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/approved.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email/Username</th>
      <th>Contact number</th>
      <th>Team</th>
      <th>Supervisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_number %></td>
        <td><%= user.team_id %></td>
        <td><%= user.supervisor_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/denied.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email/Username</th>
      <th>Contact number</th>
      <th>Team</th>
      <th>Supervisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_number %></td>
        <td><%= user.team_id %></td>
        <td><%= user.supervisor_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/edit.html.erb
<h1>Change User Details</h1>

<%= render 'form', user: @user %>

app/views/users/inactive.html.erb
<p id="notice"><%= notice %></p>

<h1>Inactive Users</h1>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email/Username</th>
      <th>Contact number</th>
      <th>Team</th>
      <th>Supervisor</th>
      <th>Activate?</th>
    </tr>
  </thead>

  <tbody>
    <% @inactive_users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_number %></td>
        <td><% unless user.team_id.nil? %> <%= link_to Team.find(user.team_id).name, Team.find(user.team_id) %><%end%></td>
        <td><% if user.supervisor_id.nil? %>
              <% if user.supervisorNameNotAUser.nil? %>
                <%= user.supervisorNameNotAUser %>
              <% end %>
            <% else %>
              <%= link_to User.find(user.supervisor_id).name, user_path(user.supervisor_id) %>
            <% end %>
        </td>
          <td><%=link_to 'Activate User', activate(user.id), method: :put%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users <%= link_to image_tag('icon/png/user.png', class: 'icon-links', title:'New User'), new_user_path %></h1>

<table class='table table-striped sortable'>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email/Username</th>
      <th>Contact number</th>
      <th>Team</th>
      <th>Supervisor</th>
      <th colspan="2" data-defaultsort='disabled'></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_number %></td>
        <td><% unless user.team_id.nil? %> <%= link_to Team.find(user.team_id).name, Team.find(user.team_id) %><%end%></td>
        <td>
        <% if user.supervisor_id.nil? %>
          <% unless user.supervisorNameNotAUser.nil? %>
            <%= user.supervisorNameNotAUser %>
          <% end %>
        <% else %>
          <%= link_to User.find(user.supervisor_id).full_name, user_path(user.supervisor_id) %>
        <% end %>
        </td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form', user: @user %>

app/views/users/notification_calendar.html.erb
<%= month_calendar(attribute: :notify_on, events: @notifications) do |day_of_month, notifs| %>
	<%= day_of_month.strftime('%-d') %>
	<% notifs.each do |note| %>
		<div>
			<%=note.notify_on.strftime('%I:%M%p') %> <%=link_to truncate(note.participant.first_name), participant_note_path(note.participant,note) %>
		</div>
	<% end %>
<% end %>

app/views/users/pending.html.erb
<p id="notice"><%= notice %></p>
<% if @pending_users.empty? %>
  <h2>Hooray! No users pending approval.</h2>
<% else %>
  <h1>Users Pending Approval</h1>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Full name</th>
        <th>Email/Username</th>
        <th>Contact number</th>
        <th>Team</th>
        <th>Supervisor</th>
        <th>Admin?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pending_users.each do |user| %>
        <tr>
          <td><%= link_to user.full_name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.contact_number %></td>
          <td><% unless user.team_id.nil? %> <%= link_to Team.find(user.team_id).name, Team.find(user.team_id) %><%end%></td>
          <td><% if user.supervisor_id.nil? %>
                <% unless user.supervisorNameNotAUser.nil? %>
                  <%= user.supervisorNameNotAUser %>
                <% end %>
              <% else %>
                <%= link_to User.find(user.supervisor_id).full_name, user_path(user.supervisor_id) %>
              <% end %>
          </td>
          <td>  <% if user.isAdmin? %>
                  <%=link_to 'Remove Admin Rights', remove_admin_rights_path(user.id), method: :put%>
                <% else %>
                  <%=link_to 'Set as Admin', add_admin_rights_path(user.id), method: :put%>
                <% end %>
          </td>
          <td><%= link_to 'Approve', approve_user_path(user.id), method: :put %></td>
          <td><%= link_to 'Reject' , reject_user_path(user.id), method: :put %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

app/views/users/reset_password.html.erb
<h1>Reset Password</h1>
<%= render 'reset_password' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p align="center">
<div class="toppad container-fluid">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= @user.full_name %>
        <%= image_tag("icon/png/key.png", size:"20x20", title:"Admin") if @user.isAdmin? %>&nbsp;&nbsp;&nbsp;
        <%= image_tag("active.png", size:"20x20", title:"Active") if @user.isActive? %>&nbsp;&nbsp;&nbsp;
        <%= image_tag("icon/png/users.png", size:"20x20", title:"Supervisor") if @user.isSupervisor? %>&nbsp;&nbsp;&nbsp;
        <%= image_tag("icon/png/checked.png", size:"20x20", title:"Approved") if (@user.isApproved? && !@user.isDenied?) %>&nbsp;&nbsp;&nbsp;
        <%= image_tag("icon/png/multiply-1.png", size:"20x20", title:"Rejected") if (@user.isDenied? && !@user.isApproved?) %>&nbsp;&nbsp;&nbsp;
        <%= image_tag("icon/png/eyeglasses.png", size:"20x20", title:"Blinded") if @user.isBlinded? %>&nbsp;&nbsp;&nbsp;
      </h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3 col-lg-3" align="center">
          <%= image_tag("https://www.barfoot.co.nz/images/noprofile-big.png", class:"img-circle img-responsive", title:"You look so cute on this one.", size:"150x150") %><br/>
          <%= link_to 'Update User', edit_user_path(@user), class:"btn btn-danger" if (@current_user.isAdmin?) || (@current_user.id == @user.id) %>
        </div>
        <div class=" col-md-9 col-lg-9 "> 
          <table class="table table-user-information table-striped">
            <tbody>
              <% if @user.email.present? %>
                <tr>
                  <td class="attribute_data">Loggr ID</td>
                  <td><%= @user.email %></td>
                </tr>
              <% end %>
              <% if @user.contact_number.present? %>
                <tr>
                  <td class="attribute_data">Contact Number</td>
                  <td><%= @user.contact_number %></td>
                </tr>
              <% end %>
              <% if @user.team_id.present? %>
                <tr>
                  <td class="attribute_data">Team</td>
                  <td>
                    <% if (@current_user.isAdmin? || (@current_user.team_id == @user.team_id)) %>
                      <%= link_to @user.team.name, team_path(@user.team_id) %>
                    <% else %>
                      <%= @user.team.name %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              <% if @user.supervisor_id.present? || @user.supervisorNameNotAUser.present? %>
                <tr>
                  <td class="attribute_data">Supervisor</td>
                  <td>
                    <% if @user.supervisor_id.nil? %>
                      <%= @user.supervisorNameNotAUser %>
                    <% else %>
                      <%= link_to User.find(@user.supervisor_id).full_name, user_path(@user.supervisor_id) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</p>
<p align="center">
  <%= link_to 'All Users', users_path, class:"btn btn-info" if @current_user.isAdmin? %>
</p>