config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :sessions
  resources :teams
  resources :studies
  resources :participants do
    resources :notes
  end
  resources :users

  root to: "users#home"
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'users/:id/home', to: 'users#home', :as => :user_home

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pending_users' => 'users#pending'
  get '/inactive_users' => 'users#inactive'
  get '/approved_users' => 'users#approved'
  get '/denied_users' => 'users#denied'
  get '/admin_users' => 'users#admin'
  get '/notification_calendar' => 'users#notification_calendar'

  put '/remove_admin_rights/:id' => 'users#remove_admin_rights', :as => :remove_admin_rights
  put '/add_admin_rights/:id' => 'users#add_admin_rights', :as => :add_admin_rights
  put '/approve_user/:id' => 'users#approve_user', :as => :approve_user
  put '/reject_user/:id' => 'users#reject_user', :as => :reject_user

  get '/reset_password' => 'users#reset_password'
  post '/reset_password' => 'users#change_password'

  get '/forgot_password' => 'users#forgot_password'
  post '/forgot_password' => 'users#request_password'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="Logging App" content="">
    <meta name="Dexter Go <dexterfgo@gmail.com>" content="">

    <title>Project Loggr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- Start of the dashboard top bar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <!-- Toggle Navigation? What is this? 
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->
          <% if @current_user.nil? %>
            <%= link_to image_tag('icon/png/house.png', class: 'icon-links', title:'Logg In'), root_path, class: 'navbar-brand' %>
            <table class=''>
              <tr class="profile_card">
                <td class="profile_card_details">
                  <br/>
                  <%= link_to 'New User?', signup_path %><br/>
                  <%= link_to 'Sign up Here!', signup_path %><br/>
                  &nbsp;
                </td>
              </tr>
            </table>
          <% else %>
            <%= link_to image_tag('icon/png/house.png', class: 'icon-links', title:'Home'), user_home_path(@current_user), class: 'navbar-brand' %>
            <table class=''>
              <tr class="profile_card">
                <td class="profile_card_details">
                  <%= link_to @current_user.full_name, user_path(@current_user.id) %><br/>
                  <%=@current_user.email%><br/>
                  <%=@current_user.contact_number%><br/>
                  Team: <%= (@current_user.team_id.nil?)? ' No Team Assigned' : (link_to @current_user.team.name, team_path(@current_user.team_id)) %>
                </td>
              </tr>
            </table>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <% unless @current_user.nil? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to image_tag('icon/png/calendar-5.png', class: 'icon-links', title:'Notification Calendar'), notification_calendar_path %></li>
              <% if @current_user.isAdmin? %>
                <li><%= link_to image_tag('icon/png/users.png', class: 'icon-links', title:'All Teams'), teams_path %></li>
              <% else %>
                <li><%= link_to image_tag('icon/png/users.png', class: 'icon-links', title:'Your Team'), team_path(@current_user.team_id) %></li>
              <% end %>
              <li><%= link_to image_tag('icon/png/user.png', class: 'icon-links', title:'Profile'), user_path(@current_user.id) %></li>
              <li><%= link_to image_tag('icon/png/exit-2.png', class: 'icon-links', title:'Logout'), logout_path %></li>
            </ul>
            <!--
            <form class="navbar-form navbar-right">
              <input type="text" class="form-control" placeholder="Search...">
            </form> -->
          <% end %>
        </div>
      </div>
    </nav>
    <!-- End of the dashboard top bar -->
    <!-- Side bar -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <% unless @current_user.nil? %>
            <ul class="nav nav-sidebar">
              <% if @current_user.isAdmin? %>
                <li><%= link_to 'View Pending Approvals', pending_users_path %></li>
                <li><%= link_to 'List All Users', users_path %></li>
              <% end %>
              <li><%= link_to "Change Password", reset_password_path +  "?token=" + Digest::MD5.hexdigest(@current_user.email) + "&email=" + @current_user.email %></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><%= link_to 'Register New Participant', new_participant_path %></li>
              <li><%= link_to 'List All Participants', participants_path %></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><%= link_to 'Add New Study', new_study_path %></li>
              <li><%= link_to 'View Existing Studies', studies_path %></li>
            </ul>
          <% end %>
        </div>
        <!-- End sidebar class="col-sm-3 col-md-2 sidebar"-->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <!-- Your content -->
              <%= yield %>
        <!-- End of your content -->
        </div> 
      </div>
    </div>
  </body>
</html>